[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
misttoken = "E7xcfMx5u8fGum2gobLLz5YqrVDQypmAyr3gCzx12c4P"

[programs.localnet]
misttoken = "E7xcfMx5u8fGum2gobLLz5YqrVDQypmAyr3gCzx12c4P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/thevapelabs.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metaplex_metadata.so"